/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type TokenParamsStruct = {
  name: string;
  symbol: string;
  baseURI: string;
};

export type TokenParamsStructOutput = [string, string, string] & {
  name: string;
  symbol: string;
  baseURI: string;
};

export type GovernorParamsStruct = {
  name: string;
  proposalThreshold: BigNumberish;
  votingDelay: BigNumberish;
  votingPeriod: BigNumberish;
  quorumNumerator: BigNumberish;
  timelockDelay: BigNumberish;
};

export type GovernorParamsStructOutput = [
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  name: string;
  proposalThreshold: BigNumber;
  votingDelay: BigNumber;
  votingPeriod: BigNumber;
  quorumNumerator: BigNumber;
  timelockDelay: BigNumber;
};

export type MinterParamsStruct = {
  maxTokens: BigNumberish;
  tokenPrice: BigNumberish;
  maxMintsPerTx: BigNumberish;
  startingBlock: BigNumberish;
  creatorShares: BigNumberish;
  daoShares: BigNumberish;
};

export type MinterParamsStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  maxTokens: BigNumber;
  tokenPrice: BigNumber;
  maxMintsPerTx: BigNumber;
  startingBlock: BigNumber;
  creatorShares: BigNumber;
  daoShares: BigNumber;
};

export interface ERC721DAODeployerInterface extends ethers.utils.Interface {
  functions: {
    "clone(address,(string,string,string),(string,uint256,uint256,uint256,uint256,uint256),(uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "governor()": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "minter()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setImplementations(address,address,address,address)": FunctionFragment;
    "timelock()": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "clone",
    values: [
      string,
      TokenParamsStruct,
      GovernorParamsStruct,
      MinterParamsStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "minter", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementations",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "clone", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "ImplementationsSet(address,address,address,address)": EventFragment;
    "NewClone(address,address,address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ImplementationsSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewClone"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type ImplementationsSetEvent = TypedEvent<
  [string, string, string, string],
  { token: string; timelock: string; governor: string; minter: string }
>;

export type ImplementationsSetEventFilter =
  TypedEventFilter<ImplementationsSetEvent>;

export type NewCloneEvent = TypedEvent<
  [string, string, string, string],
  { token: string; timelock: string; governor: string; minter: string }
>;

export type NewCloneEventFilter = TypedEventFilter<NewCloneEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ERC721DAODeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC721DAODeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    clone(
      creatorAddress: string,
      tokenParams: TokenParamsStruct,
      governorParams: GovernorParamsStruct,
      minterParams: MinterParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    minter(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setImplementations(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timelock(overrides?: CallOverrides): Promise<[string]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  clone(
    creatorAddress: string,
    tokenParams: TokenParamsStruct,
    governorParams: GovernorParamsStruct,
    minterParams: MinterParamsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  governor(overrides?: CallOverrides): Promise<string>;

  initialize(
    token_: string,
    timelock_: string,
    governor_: string,
    minter_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  minter(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setImplementations(
    token_: string,
    timelock_: string,
    governor_: string,
    minter_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timelock(overrides?: CallOverrides): Promise<string>;

  token(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    clone(
      creatorAddress: string,
      tokenParams: TokenParamsStruct,
      governorParams: GovernorParamsStruct,
      minterParams: MinterParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    governor(overrides?: CallOverrides): Promise<string>;

    initialize(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    minter(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setImplementations(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    timelock(overrides?: CallOverrides): Promise<string>;

    token(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ImplementationsSet(address,address,address,address)"(
      token?: null,
      timelock?: null,
      governor?: null,
      minter?: null
    ): ImplementationsSetEventFilter;
    ImplementationsSet(
      token?: null,
      timelock?: null,
      governor?: null,
      minter?: null
    ): ImplementationsSetEventFilter;

    "NewClone(address,address,address,address)"(
      token?: null,
      timelock?: null,
      governor?: null,
      minter?: null
    ): NewCloneEventFilter;
    NewClone(
      token?: null,
      timelock?: null,
      governor?: null,
      minter?: null
    ): NewCloneEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    clone(
      creatorAddress: string,
      tokenParams: TokenParamsStruct,
      governorParams: GovernorParamsStruct,
      minterParams: MinterParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    minter(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setImplementations(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timelock(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    clone(
      creatorAddress: string,
      tokenParams: TokenParamsStruct,
      governorParams: GovernorParamsStruct,
      minterParams: MinterParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    minter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setImplementations(
      token_: string,
      timelock_: string,
      governor_: string,
      minter_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timelock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
